# Auto generated by ct-mksetup
# Do not edit this file, edit ./project.py instead

from setuptools import setup
setup(
    **{   'author': 'Tim Diels',
    'author_email': 'timdiels.m@gmail.com',
    'classifiers': [   'Development Status :: 2 - Pre-Alpha',
                       'Environment :: X11 Applications',
                       'Environment :: X11 Applications :: Qt',
                       'Intended Audience :: End Users/Desktop',
                       'License :: OSI Approved',
                       'License :: OSI Approved :: GNU Lesser General Public License v3 (LGPLv3)',
                       'Natural Language :: English',
                       'Operating System :: POSIX',
                       'Operating System :: POSIX :: AIX',
                       'Operating System :: POSIX :: BSD',
                       'Operating System :: POSIX :: BSD :: BSD/OS',
                       'Operating System :: POSIX :: BSD :: FreeBSD',
                       'Operating System :: POSIX :: BSD :: NetBSD',
                       'Operating System :: POSIX :: BSD :: OpenBSD',
                       'Operating System :: POSIX :: GNU Hurd',
                       'Operating System :: POSIX :: HP-UX',
                       'Operating System :: POSIX :: IRIX',
                       'Operating System :: POSIX :: Linux',
                       'Operating System :: POSIX :: Other',
                       'Operating System :: POSIX :: SCO',
                       'Operating System :: POSIX :: SunOS/Solaris',
                       'Operating System :: Unix',
                       'Programming Language :: Python',
                       'Programming Language :: Python :: 3 :: Only',
                       'Programming Language :: Python :: 3',
                       'Programming Language :: Python :: 3.2',
                       'Programming Language :: Python :: 3.3',
                       'Programming Language :: Python :: 3.4',
                       'Programming Language :: Python :: 3.5',
                       'Programming Language :: Python :: Implementation',
                       'Programming Language :: Python :: Implementation :: CPython',
                       'Programming Language :: Python :: Implementation :: Stackless',
                       'Topic :: Office/Business',
                       'Topic :: Office/Business :: Scheduling'],
    'description': 'A basic cross-platform project management tool with a focus on one-man projects.',
    'entry_points': {'console_scripts': ['garage-pm = garage_pm.main:main']},
    'extras_require': {   'dev': ['sphinx', 'numpydoc', 'sphinx-rtd-theme'],
                          'test': [   'pytest',
                                      'pytest-env',
                                      'pytest-xdist',
                                      'pytest-cov',
                                      'pytest-mock',
                                      'coverage-pth']},
    'install_requires': ['chicken-turtle-util', 'click', 'pyxdg', 'more-itertools'],
    'keywords': 'office project-management',
    'license': 'LGPL3',
    'long_description': 'A basic cross-platform project management tool with a focus on one-man\n'
                        'projects with no need for resource management.\n'
                        '\n'
                        'Out of scope:\n'
                        '\n'
                        '-  Resources. We assume a single person works on the project and no\n'
                        '   resources need to be assigned. Garage PM has no clue what resources\n'
                        '   are.\n'
                        '\n'
                        'Installation\n'
                        '------------\n'
                        '\n'
                        '-  Install PyQt 5.x.x or later with your package manager or manually\n'
                        '-  Use ``python setup.py``\n'
                        '-  run with ``garage-pm``\n',
    'name': 'garage-pm',
    'package_data': {},
    'packages': ['garage_pm', 'garage_pm.tests', 'garage_pm.domain'],
    'url': 'https://github.com/timdiels/garage_pm',
    'version': '0.0.0'}
)
